import type { Metadata } from "next";
import { Manrope, Noto_Sans } from "next/font/google";
import "@fancyapps/ui/dist/fancybox/fancybox.css";
import "lenis/dist/lenis.css";
import "./globals.css";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { JsonLd } from "@/components/seo/JsonLd";
import { InotekEffects } from "@/components/inotek/InotekEffects";
import { Preloader } from "@/components/inotek/Preloader";
import { MagicCursor } from "@/components/inotek/MagicCursor";
import { SmoothScroll } from "@/components/inotek/SmoothScroll";
import { HeaderOffset } from "@/components/inotek/HeaderOffset";
import { siteConfig } from "@/config/site";
import assetVersion from "@/config/asset-version.json";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  weight: ["400", "500", "600", "700", "800"],
  display: "swap",
});

const notoSans = Noto_Sans({
  subsets: ["latin"],
  variable: "--font-noto-sans",
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL(siteConfig.url),
  title: {
    default: `${siteConfig.name} - IT Solutions & Software Engineering`,
    template: `%s | ${siteConfig.name}`,
  },
  description: siteConfig.description,
  keywords: [
    "IT Solutions Islamabad",
    "Software Development Pakistan",
    "Next.js Web Development",
    "Mobile App Engineering",
    "UI/UX Design Studio",
    "Enterprise Cloud Architecture",
    "SEO Marketing Islamabad",
    "Evolix Technologies",
  ],
  authors: [{ name: siteConfig.name, url: siteConfig.url }],
  creator: siteConfig.name,
  publisher: siteConfig.name,
  // Tab / home-screen icons come from src/app/favicon.ico, icon.svg and apple-icon.png
  // (generated by scripts/make-favicons.mjs).
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: siteConfig.url,
    title: `${siteConfig.name} - IT Solutions & Software Engineering`,
    description: siteConfig.description,
    siteName: siteConfig.name,
    images: [
      {
        url: siteConfig.ogImage,
        width: 1200,
        height: 630,
        alt: siteConfig.name,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: `${siteConfig.name} - IT Solutions & Software Engineering`,
    description: siteConfig.description,
    images: [siteConfig.ogImage],
    creator: "@evolixtech",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${manrope.variable} ${notoSans.variable}`}>
      <head>
        {/* Inotek template styles, recoloured + scoped to `.inotek` (built by scripts/build-inotek-css.mjs). */}
        {/* eslint-disable-next-line @next/next/no-css-tags -- prebuilt static file, kept out of the Tailwind pipeline on purpose */}
        <link rel="stylesheet" href={`/assets/css/inotek.css?v=${assetVersion.inotekCss}`} precedence="default" />
        <JsonLd />
      </head>
      {/* suppressHydrationWarning: browser extensions (e.g. ColorZilla) add attributes to <body>. */}
      <body className="antialiased min-h-screen flex flex-col justify-between selection:bg-[#73eb0d] selection:text-black" suppressHydrationWarning>
        <div className="inotek">
          <Preloader />
        </div>
        <Header />
        <main className="flex-1">{children}</main>
        <Footer />
        <div className="inotek" id="inotek-portal">
          <SmoothScroll />
          <MagicCursor />
        </div>
        <InotekEffects />
        <HeaderOffset />
      </body>
    </html>
  );
}
