// Paths of the photo variants generated by scripts/build-photos.mjs (one crop per template slot).

const BASE = "/assets/images/evolix";

export const projectImage = (slug: string, variant: "card" | "wide" | "detail") => `${BASE}/projects/${slug}-${variant}.webp`;
export const blogImage = (slug: string, variant: "card" | "detail" | "thumb") => `${BASE}/blog/${slug}-${variant}.webp`;
export const serviceImage = (slug: string) => `${BASE}/services/${slug}.webp`;
