export const siteConfig = {
  name: "Evolix Technologies",
  tagline: "Empowering Next-Gen Digital Innovation & IT Solutions",
  description: "Evolix Technologies provides cutting-edge IT solutions, custom web development, mobile applications, cloud architecture, UI/UX design, and digital transformation services in Islamabad & globally.",
  url: "https://evolixtechnologies.com",
  ogImage: "https://evolixtechnologies.com/og-image.jpg",
  contact: {
    address: "Islamabad, Pakistan",
    phone: "+92 313 7943362",
    email: "info@evolixtechnologies.com",
    hours: "Mon - Sat 9:00 AM - 6:30 PM, Sunday - CLOSED",
  },
  social: {
    facebook: "https://facebook.com",
    twitter: "https://twitter.com",
    linkedin: "https://linkedin.com",
    instagram: "https://instagram.com",
    github: "https://github.com",
  },
  stats: {
    experienceYears: 10,
    activeCustomers: "1.6M+",
    completedProjects: "32K+",
    satisfactionRate: "98%",
    happyClients: "10K+",
  },
  navLinks: [
    { name: "Home", href: "/" },
    { name: "About Us", href: "/about" },
    {
      name: "Services",
      href: "/services",
      submenu: [
        { name: "Custom Web Development", href: "/services/web-development" },
        { name: "Mobile App Development", href: "/services/mobile-apps" },
        { name: "UI/UX & Product Design", href: "/services/ui-ux-design" },
        { name: "SEO & Digital Marketing", href: "/services/seo-marketing" },
        { name: "Cloud & Cyber Security", href: "/services/cloud-security" },
        { name: "Domain & Hosting Solutions", href: "/services/hosting-solutions" },
      ],
    },
    { name: "Portfolio", href: "/projects" },
    { name: "Blog", href: "/blog" },
    { name: "Contact", href: "/contact" },
  ],
  services: [
    {
      id: "01",
      slug: "web-development",
      title: "Website Development",
      shortDesc: "High-performance web applications, portals, and custom SaaS platforms built with Next.js, React, and modern tech stacks.",
      icon: "/assets/images/service/hm5-icon01.webp",
      features: [
        "Full-Stack Web Engineering",
        "Next.js & React Core Architecture",
        "E-Commerce & Payment Gateways",
        "API & Cloud Microservices",
        "Lightning-Fast Performance (LCP < 1.2s)",
      ],
    },
    {
      id: "02",
      slug: "seo-marketing",
      title: "Social Media & Marketing",
      shortDesc: "Data-driven marketing campaigns, viral brand growth strategies, and multi-channel audience targeting.",
      icon: "/assets/images/service/hm5-icon02.webp",
      features: [
        "Targeted Social Media Ads",
        "Brand Identity & Positioning",
        "Influencer & Content Marketing",
        "Conversion Rate Optimization (CRO)",
        "Advanced Analytics & ROI Tracking",
      ],
    },
    {
      id: "03",
      slug: "ui-ux-design",
      title: "UI/UX Designing",
      shortDesc: "Intuitive user interfaces, immersive customer journeys, and pixel-perfect design systems in Figma.",
      icon: "/assets/images/service/hm5-icon03.webp",
      features: [
        "Wireframing & Interactive Prototyping",
        "Design Systems & Token Architecture",
        "Mobile-First Responsive Layouts",
        "Usability Testing & Accessibility",
        "3D Graphics & Micro-Animations",
      ],
    },
    {
      id: "04",
      slug: "search-engine-optimization",
      title: "Search Engine Optimization (SEO)",
      shortDesc: "Dominating Google top rankings with technical SEO, on-page optimization, and high-authority link building.",
      icon: "/assets/images/service/hm5-icon04.webp",
      features: [
        "Technical SEO & Core Web Vitals Audit",
        "Keyword Research & Search Intent Mapping",
        "Schema.org Structured Data Markup",
        "High-Authority Backlink Acquisition",
        "Local SEO & Google Business Profile",
      ],
    },
    {
      id: "05",
      slug: "cloud-security",
      title: "Domain & Hosting Solutions",
      shortDesc: "Enterprise cloud hosting, AWS/Vercel DevOps pipelines, 99.99% uptime, and military-grade cyber defense.",
      icon: "/assets/images/service/hm5-icon05.webp",
      features: [
        "Scalable Cloud Architecture (AWS, Vercel)",
        "Automated CI/CD Deployment Pipelines",
        "SSL & Cyber Threat Mitigation",
        "24/7 Server Monitoring & Backups",
        "Zero-Downtime Migration Services",
      ],
    },
    {
      id: "06",
      slug: "3d-graphics",
      title: "3D Vector & Graphic Design",
      shortDesc: "Striking 3D models, vector illustrations, motion graphics, and visual storytelling that grabs attention.",
      icon: "/assets/images/service/hm5-icon06.webp",
      features: [
        "Custom 3D Product Visualizations",
        "Vector Brand Assets & Iconography",
        "Marketing Collaterals & Pitch Decks",
        "WebGL & Interactive 3D Web Assets",
        "Motion Graphics & Explainer Assets",
      ],
    },
  ],
  projects: [
    {
      id: 1,
      title: "Webx - Modern Enterprise Platform",
      category: "Development",
      filterCategory: "development",
      image: "/assets/images/project/hm1-img01.webp",
      desc: "Architected high-throughput web platform with Next.js and automated microservices.",
      slug: "webx-enterprise-platform",
    },
    {
      id: 2,
      title: "AI-Powered Business Intelligence",
      category: "Business",
      filterCategory: "business",
      image: "/assets/images/project/hm1-img02.webp",
      desc: "Designed predictive analytics dashboards driving 4x decision speed for fintech clients.",
      slug: "business-strategy-analytics",
    },
    {
      id: 3,
      title: "Next-Gen 3D Interactive Design",
      category: "Designing",
      filterCategory: "design",
      image: "/assets/images/project/hm1-img03.webp",
      desc: "Crafted immersive 3D spatial web experience with interactive physics and WebGL shaders.",
      slug: "3d-product-design",
    },
    {
      id: 4,
      title: "Global SaaS Infrastructure",
      category: "Development",
      filterCategory: "development",
      image: "/assets/images/project/hm1-img04.webp",
      desc: "Built scalable multi-tenant SaaS application serving over 500,000 active global users.",
      slug: "global-saas-infrastructure",
    },
  ],
  team: [
    {
      id: 1,
      name: "Engr. Hamza Malik",
      role: "Chief Technology Officer",
      image: "/assets/images/team/hm5-img01.webp",
      social: { linkedin: "#", twitter: "#", github: "#" },
    },
    {
      id: 2,
      name: "Ayesha Tariq",
      role: "Lead Full-Stack Developer",
      image: "/assets/images/team/hm5-img02.webp",
      social: { linkedin: "#", twitter: "#", github: "#" },
    },
    {
      id: 3,
      name: "Zain Ali",
      role: "Principal UI/UX Designer",
      image: "/assets/images/team/hm5-img03.webp",
      social: { linkedin: "#", twitter: "#", github: "#" },
    },
    {
      id: 4,
      name: "Sara Qureshi",
      role: "SEO & Growth Strategist",
      image: "/assets/images/team/hm5-img04.webp",
      social: { linkedin: "#", twitter: "#", github: "#" },
    },
  ],
  testimonials: [
    {
      id: 1,
      quote: "Outstanding Engineering & Delivery!",
      text: "Evolix Technologies transformed our legacy system into a blazing fast modern web application. Our customer engagement doubled within the first month of release.",
      author: "David Watson",
      role: "Vice President, Global Logistics",
      rating: 5.0,
      avatar: "/assets/images/testimonial/hm4-testi03.webp",
    },
    {
      id: 2,
      quote: "Top-Tier SEO & Growth Results!",
      text: "Their technical SEO and performance optimizations helped us achieve #1 Google rankings for our primary competitive keywords. Truly a world-class team!",
      author: "Sarah Jenkins",
      role: "Head of Marketing, CloudFin",
      rating: 5.0,
      avatar: "/assets/images/testimonial/hm1-testi01.webp",
    },
    {
      id: 3,
      quote: "Pixel-Perfect UI/UX Design!",
      text: "The attention to detail and smooth micro-animations made our mobile application stand out in the marketplace. We received endless compliments from our users.",
      author: "Michael Chang",
      role: "Founder & CEO, NexaTech",
      rating: 5.0,
      avatar: "/assets/images/testimonial/hm4-testi03.webp",
    },
  ],
  blogs: [
    {
      id: 1,
      slug: "top-seo-marketing-strategies-2026",
      title: "10 Technical SEO Strategies for Dominating Search in 2026",
      category: "SEO & GROWTH",
      date: "Sep 2026",
      author: "Evolix Tech",
      image: "/assets/images/blog/blog-grid02.webp",
      excerpt: "Discover how Core Web Vitals, semantic structured data, and AI-driven content ranking algorithms shape modern Google indexing.",
    },
    {
      id: 2,
      slug: "building-scalable-saas-nextjs",
      title: "Architecting Ultra-Fast Scalable SaaS Platforms with Next.js",
      category: "DEVELOPMENT",
      date: "Sep 2026",
      author: "Evolix Tech",
      image: "/assets/images/blog/blog-grid03.webp",
      excerpt: "A deep dive into Next.js App Router, Server Components, edge caching, and database connection pooling for high-scale applications.",
    },
    {
      id: 3,
      slug: "modern-ui-ux-design-principles",
      title: "Micro-Animations & Interaction Design That Convert Users",
      category: "UI/UX DESIGN",
      date: "Sep 2026",
      author: "Evolix Tech",
      image: "/assets/images/blog/blog03.webp",
      excerpt: "Learn how subtle hover cues, fluid transitions, and accessible UI patterns significantly elevate user satisfaction and retention.",
    },
  ],
};
